### ISSUE TITLE
Icingabeat v.6.3.3 does not send the hostname for the check, instead send own hostname

### ISSUE THREAD

**Issue by 5nafu** [Icinga/icingabeat#25]
After installing icingabeat (6.3.3) on a complete new machine, with minimal changes to the icingabeat.yml and outputting to a completely new elasticsearch index (5.5), accessing an icinga2     (2.9.1), icingabeat will log checkresults with the name of the host running icingabeat as host.name:
![screenshot_2018-09-12 kibana](https://user-images.githubusercontent.com/1584089/45442823-5f62f980-b6c3-11e8-8abf-5f55eb1b06fa.png)

My icingabeat.yml (with comments, hostnames and credentials redacted):
```
icingabeat:
  host: "XXXX"
  port: 5665
  user: "XXXX"
  password: "****"
  ssl.verify: false
  eventstream.types:
    - CheckResult
    - StateChange
    - Notification
    - AcknowledgementSet
    - AcknowledgementCleared
    - CommentAdded
    - CommentRemoved
    - DowntimeAdded
    - DowntimeRemoved
    - DowntimeStarted
    - DowntimeTriggered

  eventstream.filter: ""
  eventstream.retry_interval: 10s
  statuspoller.interval: 30s
setup.dashboards.enabled: false
setup.kibana:
output.elasticsearch:
  hosts: ["XXXX:9200"]
  protocol: "https"
  username: "XXXX"
  password: "*****"

```
Representative checkresult (in json):
```
{
  "_index": "icingabeat-6.3.3-2018.09.12",
  "_type": "doc",
  "_id": "AWXO07xNOFh-eQsJ_2M4",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2018-09-12T17:27:45.615Z",
    "check_result": {
      "active": true,
      "type": "CheckResult",
      "execution_end": "2018-09-12T17:25:24.348Z",
      "check_source": "icinga2-sat...",
      "state": 0,
      "vars_before": {
        "reachable": true,
        "state": 0,
        "state_type": 1,
        "attempt": 1
      },
      "exit_status": 0,
      "output": "OK",
      "schedule_end": "2018-09-12T17:25:24.348Z",
      "ttl": 0,
      "schedule_start": "2018-09-12T17:25:23.970Z",
      "execution_start": "2018-09-12T17:25:23.970Z",
      "vars_after": {
        "reachable": true,
        "state": 0,
        "state_type": 1,
        "attempt": 1
      },
      "command": [
        "/usr/lib/nagios/custom_plugins/check_multi",
       "..."
      ]
    },
    "beat": {
      "version": "6.3.3",
      "name": "icingabeat-stg-01",
      "hostname": "icingabeat-stg-01"
    },
    "host": {
      "name": "icingabeat-stg-01"
    },
    "service": "$SERVICENAME",
    "timestamp": "2018-09-12T17:25:24.352Z",
    "type": "icingabeat.event.checkresult"
  },
  "fields": {
    "check_result.execution_end": [
      1536773124348
    ],
    "check_result.schedule_end": [
      1536773124348
    ],
    "@timestamp": [
      1536773265615
    ],
    "check_result.execution_start": [
      1536773123970
    ],
    "check_result.schedule_start": [
      1536773123970
    ],
    "timestamp": [
      1536773124352
    ]
  },
  "sort": [
    1536773265615
  ]
}
```

## Expected Behavior
Somewhere in the document should the hostname for the checkresult (notification, ...) be analog to the service.

## Current Behavior
All hostnames will be the icingabeat hostname

## Steps to Reproduce (for bugs)
1. install icingabeat as documented
2. configure icingabeat with access to icinga & elasticsearch
3. let icingabeat create the elasticsearch template `icingabeat setup`
4. restart icingabeat
5. create index patterns in kibana (and ignore error while importing kibana dashboards)
6. check resulting documents in Kibana

## Context
We can not use icingabeat 6.3.3 as there is no way to know to which of our hosts the messages are related to.

## Your Environment
* Beat version (`icingabeat -version`): icingabeat version 6.3.3 (amd64), libbeat 6.3.3
* Icinga 2 version (`icinga2 --version`): r2.9.1-1
* Elasticsearch version (`curl -XGET 'localhost:9200'`): 5.5.0
* Logstash version, if used (`bin/logstash -V`): 5.6.7 (not configured to be used)
* Kibana version, if used (`curl -XGET http://localhost:5601/status -I`):  5.5.0
* Operating System and version: Debian GNU/Linux 9.5 (stretch)
